export const GET_APARTMENTS_SUCCESS = 'GET_APARTMENTS_SUCCESS';
export const GET_APARTMENTS_ERROR = 'GET_APARTMENTS_ERROR';
export const GET_APARTMENTS_LOADING_IN_PROGRESS = 'GET_APARTMENTS_LOADING_IN_PROGRESS';
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';
export const SET_ADDRESS_PART = 'SET_ADDRESS_PART';
export const CLEAR_SEARCH_PARAMETERS = 'CLEAR_SEARCH_PARAMETERS';

export const Href_ApartmentController_GetAll = '/api/Apartment/getall';